#!/usr/bin/env -S bash
###########################################################
# @Author: dezhaoli@tencent.com
# @Date:   
# Please contact dezhaoli if you have any questions.
###########################################################


: ${XFORMAT_DIE_LOG_FILE}
: ${XFORMAT_IS_PRINT_TIME:=false}


#===========================

: ${xformat_last_seconds:=0}

#https://web.archive.org/web/20191222201924/http://www.termsys.demon.co.uk/vtansi.htm

XFORMAT_VERSION=2.2.0

XFORMAT_BLACK='\033[0;30m'
XFORMAT_RED='\033[0;31m'
XFORMAT_GREEN='\033[0;32m'
XFORMAT_YELLOW='\033[0;33m'
XFORMAT_BLUE='\033[0;34m'
XFORMAT_MAGENTA='\033[0;35m'
XFORMAT_CYAN='\033[0;36m'
XFORMAT_WHITE='\033[0;37m'
XFORMAT_NC='\033[0m'

XFORMAT_BG_BLACK='\033[0;40m'
XFORMAT_BG_RED='\033[0;41m'
XFORMAT_BG_GREEN='\033[0;42m'
XFORMAT_BG_YELLOW='\033[0;43m'
XFORMAT_BG_BLUE='\033[0;44m'
XFORMAT_BG_MAGENTA='\033[0;45m'
XFORMAT_BG_CYAN='\033[0;46m'
XFORMAT_BG_WHITE='\033[0;47m'

readonly \
        XFORMAT_VERSION \
        XFORMAT_NC \
        XFORMAT_BLACK \
        XFORMAT_RED \
        XFORMAT_GREEN \
        XFORMAT_YELLOW \
        XFORMAT_BLUE \
        XFORMAT_MAGENTA \
        XFORMAT_CYAN \
        XFORMAT_WHITE \
        XFORMAT_NC \
        XFORMAT_BG_BLACK \
        XFORMAT_BG_RED \
        XFORMAT_BG_GREEN \
        XFORMAT_BG_YELLOW \
        XFORMAT_BG_BLUE \
        XFORMAT_BG_MAGENTA \
        XFORMAT_BG_CYAN \
        XFORMAT_BG_WHITE 

#===========================

#@
function xformat-time {
  local t=$1    #@


  local d=$((t/60/60/24))
  local h=$((t/60/60%24))
  local m=$((t/60%60))
  local s=$((t%60))
  (( $d > 0 )) && printf '%d days ' $d
  (( $h > 0 )) && printf '%02d:' $h
  (( $m > 0 )) && printf '%02d:' $m
  printf '%02d\n' $s
}

function _xformat_echo() {
  if $XFORMAT_IS_PRINT_TIME ; then
    echo -e  "$(date +%T)" "[elapsed: $(xformat-time $(($SECONDS - $xformat_last_seconds )))]" "$*"
    xformat_last_seconds=$SECONDS
  else
    echo -e "$*"
  fi
}

#@ desc='echo a die message to stderr and exit'
function die() {
  set +x
  if [[ -n "$XFORMAT_DIE_LOG_FILE" && -d "$(dirname "$XFORMAT_DIE_LOG_FILE")" ]]; then
    echo "FATAL: $* " >> "$XFORMAT_DIE_LOG_FILE"
  fi
  _xformat_echo "${XFORMAT_RED}FATAL: $* ${XFORMAT_NC}" >&2
  exit 1
}

#@ desc='echo a progress message to stderr'
function progress() {
    echo "$@" >&2
}

#@ desc='echo a information message to stderr'
function info() {
  local XTRACE
  shopt -qo xtrace && set +x && XTRACE=true
  _xformat_echo "${XFORMAT_CYAN}$* ${XFORMAT_NC}" >&2
  ${XTRACE:-false} && set -x
  return 0
}

function xformat-red(){
  echo -e "${XFORMAT_RED}$* ${XFORMAT_NC}"
}
function xformat-green(){
  echo -e "${XFORMAT_GREEN}$* ${XFORMAT_NC}"
}
function xformat-yellow(){
  echo -e "${XFORMAT_YELLOW}$* ${XFORMAT_NC}"
}

#@
function xformat-file-name-size()
{
  local name="$1"  #@
  local size="$2"  #@

  ((size>0)) && printf "%50s: %15s%15s\n" "$name" "$size" "$(numfmt --to=iec --suffix=B --format="%.2f" "$size")"
  return 0
}


#@
function xformat-to-utf8-file()
{
  local path="$1"        #@
  # ____ "$@"

  
  bom=$(xxd  -l 6 -p "$path")
  if [[ $bom =~ ^fffe.* || $bom =~ ^feff.* ]]; then
    local temp_file=$(mktemp)
    iconv --from-code UTF-16 --to-code UTF-8 "$path" | tr -d '\r' > "$temp_file"
    mv -f "$temp_file" "$path"
  fi
}

