#!/usr/bin/env -S bash
###########################################################
# @Author: dezhaoli@tencent.com
# @Date:   
# Please contact dezhaoli if you have any questions.
###########################################################
. "$(which d)"


DEFAULT_KEY_VALUE_PAIR_FILE="kv_pair.txt"

_lock()
{
  local dbfile=$1

  local lockfile="${dbfile}.lock"
  trap "rm -f $lockfile" EXIT
  exec 77> "$lockfile" ||exit 1
  flock -w 5 77 || exit 1
}

_prepare()
{
    local dbfile="$1"
    mkdir -p "$(dirname "$dbfile")"
    touch "$dbfile"
}

#@
function _set()
{
    local key=                                        #@
    local value=                                      #@
    local dbfile="$DEFAULT_KEY_VALUE_PAIR_FILE"       #@ -f;--file; help='the file to which save the key-value pair'
    ____ "$@"

    # [[ -r "$dbfile" ]] && dbfile="$(realpath "$dbfile")"
    _prepare "$dbfile"

    _lock "$dbfile"
    sed -i '' "/^[[:space:]]*$key=/d" "$dbfile"
    echo "$key=$value" >> "$dbfile"
}
#@
function _get()
{
    local key=                                        #@
    local dbfile="$DEFAULT_KEY_VALUE_PAIR_FILE"       #@ -f;--file; help='the file to which save the key-value pair'
    ____ "$@"

    # [[ -r "$dbfile" ]] && dbfile="$(realpath "$dbfile")"
    _prepare "$dbfile"
    _lock "$dbfile"
    
    sed -nE "/^[[:space:]]*$key=(.*)/{s//\1/;p;q;}" "$dbfile"
}

main "_$@"